---
title: "Teaching"
---

## Current courses

- Fall 2026: EAS 31182 / MUS 31182: Music and the Problem of Climate:
  Intersections of Science, Sound, and Culture (co-taught with Sarah Politz,
  CCNY Department of Music)
- Fall 2026: CUNY Graduate Center EES 71600: Earth System Science I (co-taught)

---

## Past courses

- Spring 2026: EAS 48800 / EAS B8800 / SUS 7300B: Climate and Climate Change
- Fall 2025: [EAS 42000 / EAS A4200: Statistical Methods in Earth and Atmospheric Sciences](https://spencerahill.github.io/25f-stat-methods-course/)
- Fall 2025: CUNY Graduate Center EES 71600: Earth System Science I (co-taught)
- Spring 2025: [EAS 48800 / EAS B8800 / SUS 7300B: Climate and Climate Change](https://spencerahill.github.io/clim-change-course_2025/home.html)
- Fall 2024: EAS 30000/B1300: Earth and Environmental Science Seminar
- Spring 2024: [EAS 48800 / EAS B8800 / SUS 7300B: Climate and Climate Change](https://spencerahill.github.io/clim-change-course_2024/home.html)
- Fall 2023: [EAS 42000 / EAS A4200: Statistical Methods in Earth and Atmospheric Sciences](https://spencerahill.github.io/stat-methods-book/home.html)

---

## K-12 / public education and outreach

- Weather and Climate Livestream talk 2026-06-03, "A Wall of Smoke": <https://www.youtube.com/live/TzOi_kvajnc>
- Weather and Climate Livestream talk 2025-05-31: <https://www.youtube.com/live/RlXBjfIdl-I>
- "You Spin Me Right Round" Feb 2021 livestreamed talk for K-12 students:
  <https://www.earth.columbia.edu/videos/view/you-spin-me-right-round>
- See the [DIYnamics](https://diynamics.github.io) website for more.
