#!/usr/bin/env bash
#
# Install this repository's git hooks.
#
# Hooks live in .git/hooks, which git does not track, so a fresh clone starts
# without them. The hook scripts themselves are tracked under tools/; this
# writes the thin shims in .git/hooks that call them.
#
# Run once per clone:  bash tools/install-hooks.sh

set -euo pipefail

# Resolve the repository from where this script lives, not from the working
# directory, so that running it from elsewhere cannot install the hook into
# whatever repository the shell happens to be sitting in.
here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
root=$(git -C "$here" rev-parse --show-toplevel)
hooks="$root/.git/hooks"
mkdir -p "$hooks"

target="$hooks/pre-commit"
if [ -e "$target" ] && ! grep -q 'optimize-staged-pdfs' "$target"; then
    echo "install-hooks: $target already exists and is not ours; not overwriting" >&2
    echo "install-hooks: add this line to it yourself:" >&2
    echo '  bash "$(git rev-parse --show-toplevel)/tools/optimize-staged-pdfs.sh"' >&2
    exit 1
fi

cat > "$target" <<'EOF'
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh. Edit tools/optimize-staged-pdfs.sh.
bash "$(git rev-parse --show-toplevel)/tools/optimize-staged-pdfs.sh"
EOF
chmod +x "$target"

echo "install-hooks: wrote $target"
echo "install-hooks: skip it for one commit with  SKIP_PDF_OPT=1 git commit"
